### ISSUE TITLE
clean up parcc data to conform with r package standards

### ISSUE THREAD

**Issue by almartin82** [benjaminrobinson/LearnDC#13]
(hadley's [writeup](http://r-pkgs.had.co.nz/data.html))
- [x] move parcc to data-raw
- [x] save .csvs as .rda files
- [x] document datasets
- [ ] rework munge script into function(s)

**Comment by almartin82** [comment]
script that I used: 

```
school_parcc <- read.csv('data-raw/lea_parcc.csv', stringsAsFactors = FALSE)
lea_parcc <- read.csv('data-raw/lea_parcc.csv', stringsAsFactors = FALSE)
sector_parcc <- read.csv('data-raw/sector_parcc.csv', stringsAsFactors = FALSE)
state_parcc <- read.csv('data-raw/state_parcc.csv', stringsAsFactors = FALSE)

devtools::use_data(school_parcc, lea_parcc, sector_parcc, state_parcc)
```

**Comment by almartin82** [comment]
actually @benjaminrobinson looking at the osse_parcc_munge I'm not sure how much value there is in re-doing that as a function - it's static data, and now that we have it in the package & tidied up, it's kind of an academic exercise to write a function that does that on demand.

**Comment by almartin82** [comment]
if anything, maybe it's worth rewriting that munge as a vignette - throwing a few lines of 'this is why we are cleaning bunker hill in this way' etc

**Comment by benjaminrobinson** [comment]
I agree.  Its also a stop-gap measure until OSSE adds the PARCC results to the API!
